### ISSUE TITLE
xyz Point Cloud Northern Convention

### ISSUE THREAD

**Issue by aderaust** [3dgeo-heidelberg/vostok#1]
Perhaps this is obvious, however, in the xyz point cloud file input, what is the northern convention? Is the convention the same as the image below? (-Z North, +Z South, -X West, +X East, +Y Up, -Y Down)

![image](https://user-images.githubusercontent.com/42873794/146065526-d9376d8f-a684-4f07-8918-29952a943903.png)

**Comment by bhoefle-3dgeo** [comment]
No. X is West-East, Y is North-South, Z is elevation. Standard for LiDAR point clouds.
