### ISSUE TITLE
Point missing in files with shadow booleans ("enable shadowing" mode 2)

### ISSUE THREAD

**Issue by AntonEberhardt** [3dgeo-heidelberg/vostok#3]
Hey,

 I have noticed that if you use "enable shadowing" mode 2 (a.k.a. putting a "2" in line 14 of the configuration.sol file), the files containing the result are missing the first point of the query point cloud used as input. I tested this with a small amount of random point clouds:
 `
    import numpy as np
    import os
    
    rng = np.random.default_rng(12345)
    
    results = []
    save_path = "../generated_files/vostokTest/"
    
    for _ in range(30):
        a = np.zeros((10, 7))
        b = np.zeros((10, 6))
    
        for i in range(a.shape[0]):
            a[i, 0] += rng.integers(0, 100)
            a[i, -2] = 1
    
            b[i, 0] = 2 * i
            b[i, -3] = 1
    
        np.savetxt(save_path + "vostokTestStreet.xyz", a)
        np.savetxt(save_path + "vostokTestBuild.xyz", b)
    
        # change solfile, which specifies input for vostok
        configurate = open("./vostok_config.sol", "r").readlines()
    
        configurate[0] = str(save_path + "vostokTestBuild.xyz") + "\n"
        configurate[2] = str(save_path + "vostokTestStreet.xyz") + "\n"
        configurate[4] = str(5) + "\n"
        configurate[14] = save_path + "shadow_tile.txt\n"
    
        newfile = open("./vostok_config.sol", "w")
        newfile.writelines(configurate)
        newfile.close()
    
        # run vostok
        subprocess.run(["../vostok_fixed_build/vostok", "./vostok_config.sol"])
    
        # put Vostok shadow output in better location
        if int(configurate[13]) == 2:
    
            for vostokFile in os.listdir("./"):
                nameEnding = vostokFile.split("_")[-1]
                if nameEnding == "shadow.txt":
                    # change second argument to desired location
                    os.rename(
                        "./" + vostokFile,
                        save_path + ""
                        + vostokFile.split(".")[0]
                        + "_tile"
                        + ".txt",
                    )
    
                    print("File was moved to new location")
    
        c = np.loadtxt(save_path + "shadow_tile.txt")[:, 0]
        d = np.loadtxt(save_path + "2022_175_06-26_shadow_tile.txt")[
            :, 0
        ]
    
        results.append(np.sum(np.sort(c[1:]) - np.sort(d)))
        print(len(c), len(d))
    
    print(results)
`

Note that this already uses the version of vostok, where the file names are fixed (see pull requests).

Best regards,
Anton Eberhardt

Edit: Formatting

**Comment by omzoqasd** [comment]
FYI: special interest for HEAL project

**Comment by bhoefle-3dgeo** [comment]
Do you mean that the single point clouds containing the shadow for each time step are missing one point in their output. So the number of points is n-1 for the shadow files?

**Comment by bhoefle-3dgeo** [comment]
Problem found and solved: https://github.com/3dgeo-heidelberg/vostok/pull/5
